### ISSUE TITLE
v0.3.3 版本报 panic: invalid argument to Intn

### ISSUE THREAD

**Issue by ldwnt** [gelove/dingdong#11]
2022/04/28 23:13:31 已选择收货地址: xxx
panic: invalid argument to Intn

goroutine 19 [running]:
math/rand.(*Rand).Intn(0xc0000307e0?, 0x12?)
        /usr/local/go/src/math/rand/rand.go:168 +0x65
math/rand.Intn(...)
        /usr/local/go/src/math/rand/rand.go:337
dingdong/internal/app.Monitor()
        /source/internal/app/app.go:48 +0x8f
created by dingdong/internal/app.Run
        /source/internal/app/app.go:16 +0x35

**Comment by gelove** [comment]
你修改的参数错误，获取配置文件格式错误
