### ISSUE TITLE
获取购物车失败了

### ISSUE THREAD

**Issue by zxdstyle** [gelove/dingdong#14]
![image](https://user-images.githubusercontent.com/38398954/166099196-ae1f1c69-eff9-45a6-833b-f9076cab8b34.png)

**Comment by flyfishes** [comment]
号可能黑了，隔几天或者换一个号吧。现在抢单容易黑号。

**Comment by gelove** [comment]
旧版抢购由于叮咚多次升级已经失效，正在重构新版
当前版本请只使用监听功能
