### ISSUE TITLE
没有提交订单成功

### ISSUE THREAD

**Issue by hwlv** [gelove/dingdong#15]
<img width="775" alt="image" src="https://user-images.githubusercontent.com/29082103/166166375-b81a7d81-2e70-48f7-9c14-4b74e70d79c1.png">

**Comment by hwlv** [comment]
或者没有支付成功

**Comment by hwlv** [comment]
是否是支付的原因呢，大佬看下

**Comment by gelove** [comment]
旧版抢购由于叮咚多次升级已经失效，正在重构新版
当前版本请只使用监听功能

**Comment by gelove** [comment]
此项目已失效，有问题可以去群里问
