### ISSUE TITLE
Charles抓包叮咚买菜unknown

### ISSUE THREAD

**Issue by jinwenabc** [gelove/dingdong#16]
咨询大佬一个问题，开发的过程中是用charles抓包的吗？我装了证书，但是抓的包还是unknown，在charles官网上看到说是app没有信任证书。请问这个你是怎么解决的？

**Comment by gelove** [comment]
教程里有，更多问题请在群里提问
旧版抢购由于叮咚多次升级已经失效，正在重构新版
当前版本请只使用监听功能
