### ISSUE TITLE
windows下编译失败

### ISSUE THREAD

**Issue by figozhu** [gelove/dingdong#2]
```shell
$ make build-win
go generate ./...
GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o release/windows/dingdong ./cmd/dingdong && upx release/windows/dingdong
# dingdong/internal/app/config
internal\app\config\config.go:52:27: undefined: syscall.SIGUSR1
internal\app\config\config.go:101:17: undefined: syscall.Kill
internal\app\config\config.go:101:37: undefined: syscall.SIGUSR1
```

**Comment by gelove** [comment]
windows做兼容了，编译没问题的

**Comment by gelove** [comment]
有一个变通的方法
在 go 的安装目录修改 Go\src\syscall\types_windows.go，增加如下代码
`
var signals = [...]string{
    // 这里省略N行。。。。
  
    /** 兼容windows start */
    16: "SIGUSR1",
    17: "SIGUSR2",
    18: "SIGTSTP",
    /** 兼容windows end */
}
  
/** 兼容windows start */
func Kill(...interface{}) error {
    return nil
}

const (
    SIGUSR1 = Signal(0x10)
    SIGUSR2 = Signal(0x11)
    SIGTSTP = Signal(0x12)
)
/** 兼容windows end */
`

**Comment by gelove** [comment]
下个版本去掉信号量
