### ISSUE TITLE
执行时提示 选择session文件错误？chls文件要特别命名么？

### ISSUE THREAD

**Issue by mysy200** [gelove/dingdong#20]
执行时提示 选择session文件错误？session目录内的那个采集的dingdong.chls文件要特别命名为什么么？

**Comment by HailiangQin** [comment]
> 执行时提示 选择session文件错误？session目录内的那个采集的dingdong.chls文件要特别命名为什么么？

是chlsj格式，不是chls

**Comment by mysy200** [comment]
my mistake....  thanks.
