### ISSUE TITLE
叮咚现在还能下单吗？

### ISSUE THREAD

**Issue by jackiehj** [gelove/dingdong#24]
叮咚现在还能下单吗？

**Comment by jackiehj** [comment]
2022/05/15 06:00:37 [叮咚]订单校验失败 => {"success":false,"code":-3100,"msg":"","message":"","data":{}}: 响应错误
2022/05/15 06:00:37 Retry request => GET

**Comment by huangchexin** [comment]
同上，高峰期订单校验失败。
非高峰期切到有运力的地址报这个，实际手机上可以下单：
2022/05/15 10:24:03 [叮咚] [叮咚]获取运力失败 => {"success":false,"code":-3000,"server_time":1652581445,"is_trade":1,"msg":"抱歉人多拥挤，请稍后再试","tradeTag":"success","data":[]}: 响应错误

**Comment by gelove** [comment]
刚刚试了，没有问题
看教程 https://github.com/gelove/dingdong/blob/main/USAGE.md

**Comment by huangchexin** [comment]
2022/05/17 08:31:07 Retry request => GET https://maicai.api.ddxq.mobi/cart/index?……(此处省略)
2022/05/17 08:31:07 [叮咚]提交订单失败 => {"success":false,"code":-3001,"msg":"","message":"","data":{}}: 响应错误
2022/05/17 08:31:07 [叮咚]提交订单失败 => {"success":false,"code":-3001,"msg":"","message":"","data":{}}: 响应错误

**Comment by jackiehj** [comment]
> 刚刚试了，没有问题
> 看教程 https://github.com/gelove/dingdong/blob/main/USAGE.md

操作没问题，但是下订单的时候就会 订单校验失败。是运力不够还是？

**Comment by gelove** [comment]
在抢购时响应错误是正常的，还有你得保证在抢购时间到达之前就成功校验订单
