### ISSUE TITLE
0.31版 错误1111

### ISSUE THREAD

**Issue by zijianziye** [gelove/dingdong#8]
2022/04/28 04:30:00 无效的响应 购物车全选失败 => {"success":false,"code":1111,"msg":"您的访问已过期,请重新登录","message":"","data":null}
2022/04/28 04:30:00 无效的响应 获取购物车失败 => {"success":false,"code":1111,"msg":"您的访问已过期,请重新登录","message":"","data":null}

测试两个COOKIE都是这个问题，能读取收货地址   抓包的COOKIE还是老格式

**Comment by gelove** [comment]
如果在微信群里，可以把你的cookie发给我试试
