### ISSUE TITLE
无效的响应 获取购物车失败 

### ISSUE THREAD

**Issue by greggzj** [gelove/dingdong#9]
请大佬康康哪里出问题了？

设置其余可下单城市，修改confg.yaml中的snapup为0， 修改cookie 和ddmc-device-id和device_token字段为抓包结果，其余不变，运行go run main.go报错：
2022/04/28 20:19:16 发现可用运力[20:24-21:17](1651148655-1651151852), 请尽快下单!
2022/04/28 20:19:16 custom headers: map[string]string{"cookie":"DDXQSESSID=XXXX", "ddmc-api-version":"9.50.2", "ddmc-app-client-id":"3", "ddmc-build-version":"2.85.3", "ddmc-channel":"undefined,", "ddmc-device-id":"XXXX", "ddmc-os-version":"undefined", "referer":"https://wx.m.ddxq.mobi/", "user-agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML like Gecko) Mobile/15E148 MicroMessenger/8.0.18(0x1800123f) NetType/WIFI Language/zh_CN"}
......

2022/04/28 20:19:21 无效的响应 获取购物车失败 => {"success":false,"code":0,"msg":"","message":"","data":null}
2022/04/28 20:19:21 ===== 购物车全选成功 =====
......

**Comment by gelove** [comment]
下载新版
